# Generated by Django 4.2.6 on 2023-10-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Out Door', 'Out Door')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
